os: linux
language: go
go:
  - stable
env:
  - GO111MODULE=on
install:
  - make tools
script:
  - make test
deploy:
  provider: script
  script: echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin && make push-image
  on:
    branch: master
