name: Publish
on:
  push:
    branches:
      - master
jobs:
  test_build_publish:
    name: Test, build, and publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Export GOBIN
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Install dependencies
        run: make setup
      - name: Run tests
        run: make test
      - name: Build image
        run: make build_image
      - name: Login to Docker Hub
        if: ${{ startsWith(github.ref, 'refs/tags/v') }} # Only login for tagged commits.
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish image
        if: ${{ startsWith(github.ref, 'refs/tags/v') }} # Only publish for tagged commits.
        run: make push_image
